name: On push to main
on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  readme:
    runs-on: ubuntu-24.04
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MOMENTO_MACHINE_USER_GITHUB_TOKEN }}

      - name: Generate README
        uses: momentohq/standards-and-practices/github-actions/generate-and-commit-oss-readme@gh-actions-v2
        with:
          project_status: official
          project_stability: alpha
          project_type: other
          template_file: ./README.template.md
          output_file: ./README.md

      - name: Generate CONTRIBUTING
        uses: momentohq/standards-and-practices/github-actions/generate-and-commit-oss-readme@gh-actions-v2
        with:
          project_status: official
          project_stability: alpha
          project_type: other
          template_file: ./CONTRIBUTING.template.md
          output_file: ./CONTRIBUTING.md

  publish:
    runs-on: ubuntu-24.04

    steps:
      - uses: google-github-actions/release-please-action@v3
        name: Release Please
        id: release
        with:
          token: ${{ secrets.MOMENTO_MACHINE_USER_GITHUB_TOKEN }}
          release-type: simple
          package-name: terraform-provider-momento
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'

      - name: Publish
        run: |
          echo "Published version: ${{ steps.release.outputs.tag_name }}"
        if: ${{ steps.release.outputs.release_created }}